# This is a basic workflow to help you get started with Actions
name: "3 - Dependent Jobs"

# Controla quando o fluxo de trabalho será executado
on:
  # Dispara o workflow em eventos de solicitação push or pull mas somente para branch 'main'
  push:
    branches: [ "main", "teste**", "feature**" ]
  pull_request:
    branches: [ "main" ]
  
  # Permite que você execute este workflow manualmente na tab Actions
  workflow_dispatch:

# Uma execução de workflow é composta por um ou mais jobs que podem ser executados sequencialmente ou em paralelo
jobs:
  # Este workflow contem dois jobs chamados "build" e "explore-github-actions"
  build:
    # O tipo de executor (runner) no qual o job será executado
    runs-on: ubuntu-latest
    name: build

    # Steps representam uma sequencia de tarefas (tasks) que serão executados como parte de um job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository code
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  explore-github-actions:
    runs-on: ubuntu-latest
    name: explore-github-actions
    # needs identifica que qualquer job deve ser concluido com sucesso antes deste job (explore-github-actions) ser executado
    # Esse código pode ser uma string ou array de strings. Se houver falha em um job, todos os jobs que dependem dele serão ignorados, 
    # a menos que os jobs usem uma expressão condicional que faça o job continuar.
    needs: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: executing some runs
        run: | 
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."      
          echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
          echo "🖥️ The workflow is now ready to test your code on the runner."
          echo "This repository belongs to ${{ github.repository_owner }}"
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          
      - run: echo "🍏 This job's status is ${{ job.status }}."
  
    
